# Generated by Django 5.0 on 2025-09-28 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movierequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movierequest",
            name="votes",
            field=models.ManyToManyField(
                blank=True,
                related_name="movie_request_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
